[package]
name = "introsort"
version = "0.3.0"
authors = [ "Viktor Dahl <pazaconyoman@gmail.com>" ]
description = "Fast sorting compatible with no_std."
license = "Apache-2.0"
repository = "https://github.com/veddan/rust-introsort"
readme = "README.md"

[features]
default = [ "float" ]
float = []

[lib]
name = "introsort"
path = "src/lib.rs"
test = false
bench = false

[dev-dependencies]
rand = "0.3.7"

[profile.test]
opt-level = 1
