[package]
name = "introsort"
version = "0.3.0"
authors = [ "Viktor Dahl <pazaconyoman@gmail.com>" ]

[lib]
name = "introsort"
path = "src/lib.rs"
test = false
bench = false

[dev-dependencies]
rand = "0.3.4"
